inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable

require:
  - rubocop-minitest
  - rubocop-rake

Metrics/MethodLength:
  Exclude:
    - test/bot_message_formatter_test.rb
    - test/channel_info_test.rb

Metrics/ClassLength:
  Exclude:
    - test/channel_info_test.rb

Layout/LineLength:
  Exclude:
    - test/bot_message_formatter_test.rb
